spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernatedb
    username: root
    password: rootPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
